// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tpqjbmpxmhuqrribtist.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRwcWpibXB4bWh1cXJyaWJ0aXN0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQzMTI2NDQsImV4cCI6MjA2OTg4ODY0NH0.e5hvxtbxrpCHioWYvMzpL3aXMe-D29wrzOWJZevnZsM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});